"""Phase presets for training the Taluy roll expert policy."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RollCurriculumStage:
    """Static curriculum phase applied when building a roll environment."""

    name: str
    description: str
    target_roll_deg: float
    episode_length_s: float
    settle_window_s: float
    k_prog: float
    k_xy: float
    k_pitch: float
    k_yaw: float
    k_depth: float
    k_smooth: float
    excess_pitch_deg: float
    excess_depth_error_m: float
    excess_xy_drift_m: float
    settle_pitch_limit_deg: float
    settle_yaw_limit_deg: float
    settle_ang_vel_limit_rad_s: float
    settle_depth_error_limit_m: float
    settle_xy_drift_limit_m: float | None = None
    terminal_success_weight: float = 100.0
    terminal_failure_weight: float = -50.0
    k_action_effort: float = 0.0
    k_thruster_saturation: float = 0.0
    k_post_target_roll_through_torque: float = 0.0
    thruster_saturation_threshold: float = 0.85

    def roll_env_kwargs(self) -> dict[str, float]:
        """Return keyword arguments consumed by ``make_roll_env_cfg``."""
        return {
            "target_roll_deg": self.target_roll_deg,
            "settle_window_s": self.settle_window_s,
            "k_prog": self.k_prog,
            "k_xy": self.k_xy,
            "k_pitch": self.k_pitch,
            "k_yaw": self.k_yaw,
            "k_depth": self.k_depth,
            "k_smooth": self.k_smooth,
            "k_action_effort": self.k_action_effort,
            "k_thruster_saturation": self.k_thruster_saturation,
            "k_post_target_roll_through_torque": (
                self.k_post_target_roll_through_torque
            ),
            "thruster_saturation_threshold": self.thruster_saturation_threshold,
            "excess_pitch_deg": self.excess_pitch_deg,
            "excess_depth_error_m": self.excess_depth_error_m,
            "excess_xy_drift_m": self.excess_xy_drift_m,
            "settle_pitch_limit_deg": self.settle_pitch_limit_deg,
            "settle_yaw_limit_deg": self.settle_yaw_limit_deg,
            "settle_ang_vel_limit_rad_s": self.settle_ang_vel_limit_rad_s,
            "settle_depth_error_limit_m": self.settle_depth_error_limit_m,
            "settle_xy_drift_limit_m": self.settle_xy_drift_limit_m,
            "terminal_success_weight": self.terminal_success_weight,
            "terminal_failure_weight": self.terminal_failure_weight,
        }


ROLL_CURRICULUM_STAGES: dict[str, RollCurriculumStage] = {
    "c0_90_discovery": RollCurriculumStage(
        name="c0_90_discovery",
        description="Discover that positive body roll torque increases phi_total.",
        target_roll_deg=90.0,
        episode_length_s=8.0,
        settle_window_s=0.1,
        k_prog=10.0,
        k_xy=0.0,
        k_pitch=0.2,
        k_yaw=0.05,
        k_depth=0.1,
        k_smooth=0.001,
        excess_pitch_deg=89.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=4.0,
        settle_depth_error_limit_m=2.0,
        terminal_success_weight=60.0,
        terminal_failure_weight=-20.0,
    ),
    "c1_180_inversion": RollCurriculumStage(
        name="c1_180_inversion",
        description="Reach inverted attitude while keeping catastrophic errors bounded.",
        target_roll_deg=180.0,
        episode_length_s=10.0,
        settle_window_s=0.1,
        k_prog=8.0,
        k_xy=0.0,
        k_pitch=0.4,
        k_yaw=0.1,
        k_depth=0.3,
        k_smooth=0.002,
        excess_pitch_deg=89.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=4.0,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=80.0,
        terminal_failure_weight=-30.0,
    ),
    "c2_360_full_turn": RollCurriculumStage(
        name="c2_360_full_turn",
        description="Complete one full roll with moderate attitude/depth discipline.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.2,
        k_prog=6.0,
        k_xy=0.0,
        k_pitch=0.6,
        k_yaw=0.2,
        k_depth=0.6,
        k_smooth=0.005,
        excess_pitch_deg=85.0,
        excess_depth_error_m=1.5,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=25.0,
        settle_yaw_limit_deg=50.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=100.0,
        terminal_failure_weight=-40.0,
    ),
    "c2a_360_reach": RollCurriculumStage(
        name="c2a_360_reach",
        description="Reach one full roll with a shorter settle confirmation.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.5,
        k_yaw=0.6,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=70.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=6.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=150.0,
        terminal_failure_weight=-40.0,
    ),
    "c2r1_360_reach_light": RollCurriculumStage(
        name="c2r1_360_reach_light",
        description="Reach one full roll with light attitude discipline.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.02,
        k_prog=8.0,
        k_xy=0.01,
        k_pitch=0.6,
        k_yaw=0.2,
        k_depth=0.4,
        k_smooth=0.004,
        excess_pitch_deg=80.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=150.0,
        terminal_failure_weight=-30.0,
    ),
    "c2r2_360_short_settle": RollCurriculumStage(
        name="c2r2_360_short_settle",
        description="Preserve 360 reach while extending the settle confirmation.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.05,
        k_prog=8.0,
        k_xy=0.02,
        k_pitch=0.8,
        k_yaw=0.25,
        k_depth=0.5,
        k_smooth=0.005,
        excess_pitch_deg=78.0,
        excess_depth_error_m=1.6,
        excess_xy_drift_m=7.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=170.0,
        terminal_failure_weight=-35.0,
    ),
    "c2r3_360_stable_settle": RollCurriculumStage(
        name="c2r3_360_stable_settle",
        description="Consolidate 360 roll with a longer settle confirmation.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.1,
        k_prog=8.0,
        k_xy=0.02,
        k_pitch=1.0,
        k_yaw=0.35,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=75.0,
        excess_depth_error_m=1.5,
        excess_xy_drift_m=7.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),
    "c2b_360_hold_0p05": RollCurriculumStage(
        name="c2b_360_hold_0p05",
        description="Extend the successful 360 reach policy to a 0.05 s hold.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.5,
        k_yaw=0.6,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=70.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=6.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c2c_360_hold_0p10": RollCurriculumStage(
        name="c2c_360_hold_0p10",
        description="Extend the 360 hold curriculum to a 0.10 s settle window.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.5,
        k_yaw=0.6,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=70.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=6.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),
    "c3a_540_reach_0p05": RollCurriculumStage(
        name="c3a_540_reach_0p05",
        description="Bridge from one full roll toward two rolls with a 540 deg target.",
        target_roll_deg=540.0,
        episode_length_s=17.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.2,
        k_yaw=0.5,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=75.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=7.0,
        settle_pitch_limit_deg=40.0,
        settle_yaw_limit_deg=70.0,
        settle_ang_vel_limit_rad_s=3.0,
        settle_depth_error_limit_m=1.2,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3b_720_reach_0p02": RollCurriculumStage(
        name="c3b_720_reach_0p02",
        description="Probe direct two-roll reach with only a very short confirmation.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3c_720_reach_loose_control": RollCurriculumStage(
        name="c3c_720_reach_loose_control",
        description="Re-test direct 720 reach from the best 360 hold baseline.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3d_720_reach_xy_moderate": RollCurriculumStage(
        name="c3d_720_reach_xy_moderate",
        description="Keep the short 720 reach task but push down XY drift.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.06,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3e_720_hold_0p05_xy_light": RollCurriculumStage(
        name="c3e_720_hold_0p05_xy_light",
        description="Ask for a short 720 hold while lightly penalizing XY drift.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.04,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),

    "c3g_720_hold_0p05_xy_recover": RollCurriculumStage(
        name="c3g_720_hold_0p05_xy_recover",
        description="Keep the C3E 720 short-hold behavior while reducing terminal XY drift.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.10,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=4.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),

    "c3h_720_hold_0p05_xy_tight": RollCurriculumStage(
        name="c3h_720_hold_0p05_xy_tight",
        description="Keep the C3E 720 short-hold behavior while reducing terminal XY drift.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.15,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=1.25,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),
    "c3i_720_hold_0p10_sat005": RollCurriculumStage(
        name="c3i_720_hold_0p10_sat005",
        description="Low-saturation 720 hold probe with light thruster-limit cost.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.15,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.010,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=1.25,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
        k_action_effort=0.003,
        k_thruster_saturation=0.05,
        thruster_saturation_threshold=0.85,
    ),
    "c3i_720_hold_0p10_sat010": RollCurriculumStage(
        name="c3i_720_hold_0p10_sat010",
        description="Low-saturation 720 hold probe with medium thruster-limit cost.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.15,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.010,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=1.25,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
        k_action_effort=0.003,
        k_thruster_saturation=0.10,
        thruster_saturation_threshold=0.85,
    ),
    "c3i_720_hold_0p10_sat020": RollCurriculumStage(
        name="c3i_720_hold_0p10_sat020",
        description="Low-saturation 720 hold probe with strong thruster-limit cost.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.15,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.010,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=1.25,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
        k_action_effort=0.003,
        k_thruster_saturation=0.20,
        thruster_saturation_threshold=0.85,
    ),
    "c3j_720_polish": RollCurriculumStage(
        name="c3j_720_polish",
        description=(
            "Polish 720 hold from sat010: harder attitude/saturation discipline, tighter settle, "
            "to bridge toward c4 deployment quality."
        ),
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.25,
        k_prog=5.0,
        k_xy=0.25,
        k_pitch=2.0,
        k_yaw=0.8,
        k_depth=0.8,
        k_smooth=0.030,
        excess_pitch_deg=70.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=30.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=1.5,
        settle_depth_error_limit_m=0.8,
        settle_xy_drift_limit_m=0.7,
        terminal_success_weight=200.0,
        terminal_failure_weight=-40.0,
        k_action_effort=0.005,
        k_thruster_saturation=0.30,
        thruster_saturation_threshold=0.75,
    ),
    "c3k_720_soft_polish": RollCurriculumStage(
        name="c3k_720_soft_polish",
        description="Safer 720 polish from c3i sat010 that keeps roll progress and tightens attitude/depth gradually.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.15,
        k_prog=6.0,
        k_xy=0.18,
        k_pitch=1.35,
        k_yaw=0.55,
        k_depth=0.60,
        k_smooth=0.014,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=40.0,
        settle_yaw_limit_deg=80.0,
        settle_ang_vel_limit_rad_s=1.8,
        settle_depth_error_limit_m=1.2,
        settle_xy_drift_limit_m=1.05,
        terminal_success_weight=200.0,
        terminal_failure_weight=-45.0,
        k_action_effort=0.0035,
        k_thruster_saturation=0.12,
        thruster_saturation_threshold=0.85,
    ),
    "c3l_720_xy_guard": RollCurriculumStage(
        name="c3l_720_xy_guard",
        description="Isolate XY drift control from c3i sat010 while keeping attitude and saturation pressure near the base stage.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.10,
        k_prog=6.0,
        k_xy=0.28,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.55,
        k_smooth=0.010,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=0.9,
        terminal_success_weight=220.0,
        terminal_failure_weight=-55.0,
        k_action_effort=0.003,
        k_thruster_saturation=0.10,
        thruster_saturation_threshold=0.85,
    ),
    "c3m_720_smooth_sat_guard": RollCurriculumStage(
        name="c3m_720_smooth_sat_guard",
        description="Reduce saturation and action roughness from c3i sat010 while keeping success conditions close to the base stage.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.10,
        k_prog=6.0,
        k_xy=0.16,
        k_pitch=1.10,
        k_yaw=0.45,
        k_depth=0.55,
        k_smooth=0.020,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.5,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=1.25,
        terminal_success_weight=200.0,
        terminal_failure_weight=-45.0,
        k_action_effort=0.006,
        k_thruster_saturation=0.15,
        thruster_saturation_threshold=0.85,
    ),
    "c3n_720_c3l_sat_soft": RollCurriculumStage(
        name="c3n_720_c3l_sat_soft",
        description="Continue from c3l with the same XY guard while adding a moderate saturation and smoothness pressure.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.10,
        k_prog=6.0,
        k_xy=0.28,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.55,
        k_smooth=0.014,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=0.9,
        terminal_success_weight=220.0,
        terminal_failure_weight=-55.0,
        k_action_effort=0.004,
        k_thruster_saturation=0.20,
        thruster_saturation_threshold=0.85,
    ),
    "c3o_720_c3l_sat_threshold": RollCurriculumStage(
        name="c3o_720_c3l_sat_threshold",
        description="Continue from c3l with a lower saturation threshold and slightly relaxed XY pressure to test lower-thrust solutions.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.10,
        k_prog=6.0,
        k_xy=0.24,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.55,
        k_smooth=0.016,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.25,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=1.0,
        terminal_success_weight=210.0,
        terminal_failure_weight=-50.0,
        k_action_effort=0.0045,
        k_thruster_saturation=0.25,
        thruster_saturation_threshold=0.80,
    ),
    "c3p_720_c3l_deploy_polish": RollCurriculumStage(
        name="c3p_720_c3l_deploy_polish",
        description="Continue from c3l toward deployment quality by keeping tight XY while improving attitude, depth, smoothness, and saturation.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.15,
        k_prog=5.5,
        k_xy=0.30,
        k_pitch=1.25,
        k_yaw=0.50,
        k_depth=0.65,
        k_smooth=0.016,
        excess_pitch_deg=78.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.0,
        settle_pitch_limit_deg=40.0,
        settle_yaw_limit_deg=80.0,
        settle_ang_vel_limit_rad_s=1.6,
        settle_depth_error_limit_m=1.2,
        settle_xy_drift_limit_m=0.8,
        terminal_success_weight=230.0,
        terminal_failure_weight=-55.0,
        k_action_effort=0.0045,
        k_thruster_saturation=0.20,
        thruster_saturation_threshold=0.80,
    ),
    "c3q_720_c3l_strict_settle": RollCurriculumStage(
        name="c3q_720_c3l_strict_settle",
        description="Continue from c3l toward strict deploy settle quality with a longer hold, tight attitude, and low angular velocity.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.50,
        k_prog=5.5,
        k_xy=0.35,
        k_pitch=1.50,
        k_yaw=0.75,
        k_depth=0.80,
        k_smooth=0.018,
        excess_pitch_deg=75.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.0,
        settle_pitch_limit_deg=15.0,
        settle_yaw_limit_deg=15.0,
        settle_ang_vel_limit_rad_s=0.2617993877991494,
        settle_depth_error_limit_m=0.30,
        settle_xy_drift_limit_m=0.50,
        terminal_success_weight=240.0,
        terminal_failure_weight=-60.0,
        k_action_effort=0.005,
        k_thruster_saturation=0.20,
        thruster_saturation_threshold=0.80,
    ),
    "c3r_720_post_target_tx_brake": RollCurriculumStage(
        name="c3r_720_post_target_tx_brake",
        description="Preserve c3l reach while penalizing same-direction roll torque after the 720 target is reached.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.15,
        k_prog=6.0,
        k_xy=0.28,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.55,
        k_smooth=0.012,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=2.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.5,
        settle_xy_drift_limit_m=0.9,
        terminal_success_weight=220.0,
        terminal_failure_weight=-55.0,
        k_action_effort=0.003,
        k_thruster_saturation=0.10,
        k_post_target_roll_through_torque=0.03,
        thruster_saturation_threshold=0.85,
    ),
    "c3f_720_hold_0p10_soft": RollCurriculumStage(
        name="c3f_720_hold_0p10_soft",
        description="Probe whether 720 reach survives a soft 0.10 s hold.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.05,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=190.0,
        terminal_failure_weight=-40.0,
    ),
    "c3_720_no_hard_stop": RollCurriculumStage(
        name="c3_720_no_hard_stop",
        description="Complete two rolls without requiring a precise final stop.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.2,
        k_prog=5.0,
        k_xy=0.0,
        k_pitch=0.8,
        k_yaw=0.3,
        k_depth=0.8,
        k_smooth=0.008,
        excess_pitch_deg=82.0,
        excess_depth_error_m=1.25,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=18.0,
        settle_yaw_limit_deg=30.0,
        settle_ang_vel_limit_rad_s=1.5,
        settle_depth_error_limit_m=0.6,
        terminal_success_weight=100.0,
        terminal_failure_weight=-50.0,
    ),
    "c4_720_settle": RollCurriculumStage(
        name="c4_720_settle",
        description="Complete two rolls and settle for nominal deployment quality.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=1.0,
        k_prog=4.0,
        k_xy=0.05,
        k_pitch=1.0,
        k_yaw=0.5,
        k_depth=1.0,
        k_smooth=0.01,
        excess_pitch_deg=80.0,
        excess_depth_error_m=1.0,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=10.0,
        settle_yaw_limit_deg=15.0,
        settle_ang_vel_limit_rad_s=0.25,
        settle_depth_error_limit_m=0.15,
        terminal_success_weight=100.0,
        terminal_failure_weight=-50.0,
    ),
}


def get_roll_curriculum_stage(name: str) -> RollCurriculumStage:
    """Return a named roll curriculum stage or raise a helpful error."""
    try:
        return ROLL_CURRICULUM_STAGES[name]
    except KeyError as exc:
        names = ", ".join(sorted(ROLL_CURRICULUM_STAGES))
        raise ValueError(f"Unknown roll curriculum stage '{name}'. Choices: {names}.") from exc


__all__ = [
    "ROLL_CURRICULUM_STAGES",
    "RollCurriculumStage",
    "get_roll_curriculum_stage",
]
