"""Phase presets for training the Taluy roll expert policy."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RollCurriculumStage:
    """Static curriculum phase applied when building a roll environment."""

    name: str
    description: str
    target_roll_deg: float
    episode_length_s: float
    settle_window_s: float
    k_prog: float
    k_xy: float
    k_pitch: float
    k_yaw: float
    k_depth: float
    k_smooth: float
    excess_pitch_deg: float
    excess_depth_error_m: float
    excess_xy_drift_m: float
    settle_pitch_limit_deg: float
    settle_yaw_limit_deg: float
    settle_ang_vel_limit_rad_s: float
    settle_depth_error_limit_m: float
    terminal_success_weight: float = 100.0
    terminal_failure_weight: float = -50.0

    def roll_env_kwargs(self) -> dict[str, float]:
        """Return keyword arguments consumed by ``make_roll_env_cfg``."""
        return {
            "target_roll_deg": self.target_roll_deg,
            "settle_window_s": self.settle_window_s,
            "k_prog": self.k_prog,
            "k_xy": self.k_xy,
            "k_pitch": self.k_pitch,
            "k_yaw": self.k_yaw,
            "k_depth": self.k_depth,
            "k_smooth": self.k_smooth,
            "excess_pitch_deg": self.excess_pitch_deg,
            "excess_depth_error_m": self.excess_depth_error_m,
            "excess_xy_drift_m": self.excess_xy_drift_m,
            "settle_pitch_limit_deg": self.settle_pitch_limit_deg,
            "settle_yaw_limit_deg": self.settle_yaw_limit_deg,
            "settle_ang_vel_limit_rad_s": self.settle_ang_vel_limit_rad_s,
            "settle_depth_error_limit_m": self.settle_depth_error_limit_m,
            "terminal_success_weight": self.terminal_success_weight,
            "terminal_failure_weight": self.terminal_failure_weight,
        }


ROLL_CURRICULUM_STAGES: dict[str, RollCurriculumStage] = {
    "c0_90_discovery": RollCurriculumStage(
        name="c0_90_discovery",
        description="Discover that positive body roll torque increases phi_total.",
        target_roll_deg=90.0,
        episode_length_s=8.0,
        settle_window_s=0.1,
        k_prog=10.0,
        k_xy=0.0,
        k_pitch=0.2,
        k_yaw=0.05,
        k_depth=0.1,
        k_smooth=0.001,
        excess_pitch_deg=89.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=4.0,
        settle_depth_error_limit_m=2.0,
        terminal_success_weight=60.0,
        terminal_failure_weight=-20.0,
    ),
    "c1_180_inversion": RollCurriculumStage(
        name="c1_180_inversion",
        description="Reach inverted attitude while keeping catastrophic errors bounded.",
        target_roll_deg=180.0,
        episode_length_s=10.0,
        settle_window_s=0.1,
        k_prog=8.0,
        k_xy=0.0,
        k_pitch=0.4,
        k_yaw=0.1,
        k_depth=0.3,
        k_smooth=0.002,
        excess_pitch_deg=89.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=4.0,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=80.0,
        terminal_failure_weight=-30.0,
    ),
    "c2_360_full_turn": RollCurriculumStage(
        name="c2_360_full_turn",
        description="Complete one full roll with moderate attitude/depth discipline.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.2,
        k_prog=6.0,
        k_xy=0.0,
        k_pitch=0.6,
        k_yaw=0.2,
        k_depth=0.6,
        k_smooth=0.005,
        excess_pitch_deg=85.0,
        excess_depth_error_m=1.5,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=25.0,
        settle_yaw_limit_deg=50.0,
        settle_ang_vel_limit_rad_s=2.0,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=100.0,
        terminal_failure_weight=-40.0,
    ),
    "c2a_360_reach": RollCurriculumStage(
        name="c2a_360_reach",
        description="Reach one full roll with a shorter settle confirmation.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.5,
        k_yaw=0.6,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=70.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=6.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=150.0,
        terminal_failure_weight=-40.0,
    ),
    "c2r1_360_reach_light": RollCurriculumStage(
        name="c2r1_360_reach_light",
        description="Reach one full roll with light attitude discipline.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.02,
        k_prog=8.0,
        k_xy=0.01,
        k_pitch=0.6,
        k_yaw=0.2,
        k_depth=0.4,
        k_smooth=0.004,
        excess_pitch_deg=80.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=150.0,
        terminal_failure_weight=-30.0,
    ),
    "c2r2_360_short_settle": RollCurriculumStage(
        name="c2r2_360_short_settle",
        description="Preserve 360 reach while extending the settle confirmation.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.05,
        k_prog=8.0,
        k_xy=0.02,
        k_pitch=0.8,
        k_yaw=0.25,
        k_depth=0.5,
        k_smooth=0.005,
        excess_pitch_deg=78.0,
        excess_depth_error_m=1.6,
        excess_xy_drift_m=7.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=170.0,
        terminal_failure_weight=-35.0,
    ),
    "c2r3_360_stable_settle": RollCurriculumStage(
        name="c2r3_360_stable_settle",
        description="Consolidate 360 roll with a longer settle confirmation.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.1,
        k_prog=8.0,
        k_xy=0.02,
        k_pitch=1.0,
        k_yaw=0.35,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=75.0,
        excess_depth_error_m=1.5,
        excess_xy_drift_m=7.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),
    "c2b_360_hold_0p05": RollCurriculumStage(
        name="c2b_360_hold_0p05",
        description="Extend the successful 360 reach policy to a 0.05 s hold.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.5,
        k_yaw=0.6,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=70.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=6.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c2c_360_hold_0p10": RollCurriculumStage(
        name="c2c_360_hold_0p10",
        description="Extend the 360 hold curriculum to a 0.10 s settle window.",
        target_roll_deg=360.0,
        episode_length_s=14.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.5,
        k_yaw=0.6,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=70.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=6.0,
        settle_pitch_limit_deg=35.0,
        settle_yaw_limit_deg=60.0,
        settle_ang_vel_limit_rad_s=2.5,
        settle_depth_error_limit_m=1.0,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),
    "c3a_540_reach_0p05": RollCurriculumStage(
        name="c3a_540_reach_0p05",
        description="Bridge from one full roll toward two rolls with a 540 deg target.",
        target_roll_deg=540.0,
        episode_length_s=17.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.2,
        k_yaw=0.5,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=75.0,
        excess_depth_error_m=1.8,
        excess_xy_drift_m=7.0,
        settle_pitch_limit_deg=40.0,
        settle_yaw_limit_deg=70.0,
        settle_ang_vel_limit_rad_s=3.0,
        settle_depth_error_limit_m=1.2,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3b_720_reach_0p02": RollCurriculumStage(
        name="c3b_720_reach_0p02",
        description="Probe direct two-roll reach with only a very short confirmation.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3c_720_reach_loose_control": RollCurriculumStage(
        name="c3c_720_reach_loose_control",
        description="Re-test direct 720 reach from the best 360 hold baseline.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.02,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3d_720_reach_xy_moderate": RollCurriculumStage(
        name="c3d_720_reach_xy_moderate",
        description="Keep the short 720 reach task but push down XY drift.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.02,
        k_prog=6.0,
        k_xy=0.06,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=170.0,
        terminal_failure_weight=-40.0,
    ),
    "c3e_720_hold_0p05_xy_light": RollCurriculumStage(
        name="c3e_720_hold_0p05_xy_light",
        description="Ask for a short 720 hold while lightly penalizing XY drift.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.05,
        k_prog=6.0,
        k_xy=0.04,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=180.0,
        terminal_failure_weight=-40.0,
    ),
    "c3f_720_hold_0p10_soft": RollCurriculumStage(
        name="c3f_720_hold_0p10_soft",
        description="Probe whether 720 reach survives a soft 0.10 s hold.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.1,
        k_prog=6.0,
        k_xy=0.05,
        k_pitch=1.0,
        k_yaw=0.4,
        k_depth=0.5,
        k_smooth=0.006,
        excess_pitch_deg=80.0,
        excess_depth_error_m=2.0,
        excess_xy_drift_m=8.0,
        settle_pitch_limit_deg=45.0,
        settle_yaw_limit_deg=90.0,
        settle_ang_vel_limit_rad_s=3.5,
        settle_depth_error_limit_m=1.5,
        terminal_success_weight=190.0,
        terminal_failure_weight=-40.0,
    ),
    "c3_720_no_hard_stop": RollCurriculumStage(
        name="c3_720_no_hard_stop",
        description="Complete two rolls without requiring a precise final stop.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=0.2,
        k_prog=5.0,
        k_xy=0.0,
        k_pitch=0.8,
        k_yaw=0.3,
        k_depth=0.8,
        k_smooth=0.008,
        excess_pitch_deg=82.0,
        excess_depth_error_m=1.25,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=18.0,
        settle_yaw_limit_deg=30.0,
        settle_ang_vel_limit_rad_s=1.5,
        settle_depth_error_limit_m=0.6,
        terminal_success_weight=100.0,
        terminal_failure_weight=-50.0,
    ),
    "c4_720_settle": RollCurriculumStage(
        name="c4_720_settle",
        description="Complete two rolls and settle for nominal deployment quality.",
        target_roll_deg=720.0,
        episode_length_s=20.0,
        settle_window_s=1.0,
        k_prog=4.0,
        k_xy=0.05,
        k_pitch=1.0,
        k_yaw=0.5,
        k_depth=1.0,
        k_smooth=0.01,
        excess_pitch_deg=80.0,
        excess_depth_error_m=1.0,
        excess_xy_drift_m=10.0,
        settle_pitch_limit_deg=10.0,
        settle_yaw_limit_deg=15.0,
        settle_ang_vel_limit_rad_s=0.25,
        settle_depth_error_limit_m=0.15,
        terminal_success_weight=100.0,
        terminal_failure_weight=-50.0,
    ),
}


def get_roll_curriculum_stage(name: str) -> RollCurriculumStage:
    """Return a named roll curriculum stage or raise a helpful error."""
    try:
        return ROLL_CURRICULUM_STAGES[name]
    except KeyError as exc:
        names = ", ".join(sorted(ROLL_CURRICULUM_STAGES))
        raise ValueError(f"Unknown roll curriculum stage '{name}'. Choices: {names}.") from exc


__all__ = [
    "ROLL_CURRICULUM_STAGES",
    "RollCurriculumStage",
    "get_roll_curriculum_stage",
]
