from mjlab.envs.mdp import base_ang_vel, base_lin_vel

from .observations import (
    base_quat_wxyz,
    depth_error_from_ref,
    last_body_wrench_action,
    phi_total_norm,
    xy_error_w,
)
from .metrics import (
    body_wrench_action_l2,
    body_wrench_saturation_fraction,
    depth_abs_error_m,
    hydro_wrench_norm,
    phi_total_rad,
    pitch_abs_rad,
    roll_progress_ratio,
    root_ang_speed_rad_s,
    settle_counter_s,
    target_reached,
    water_current_speed_m_s,
    xy_drift_m,
    yaw_abs_error_rad,
)
from .rewards import (
    body_wrench_action_rate_l2,
    depth_hold_penalty,
    pitch_penalty,
    roll_progress,
    terminal_failure_reward,
    terminal_success_reward,
    xy_drift_penalty,
    yaw_hold_penalty,
)
from .terminations import (
    excess_depth_error,
    excess_pitch,
    excess_xy_drift,
    roll_task_success,
)

__all__ = [
    "base_ang_vel",
    "base_lin_vel",
    "base_quat_wxyz",
    "body_wrench_action_l2",
    "body_wrench_action_rate_l2",
    "body_wrench_saturation_fraction",
    "depth_abs_error_m",
    "depth_error_from_ref",
    "depth_hold_penalty",
    "excess_depth_error",
    "excess_pitch",
    "excess_xy_drift",
    "hydro_wrench_norm",
    "last_body_wrench_action",
    "phi_total_rad",
    "phi_total_norm",
    "pitch_penalty",
    "pitch_abs_rad",
    "roll_progress",
    "roll_progress_ratio",
    "roll_task_success",
    "root_ang_speed_rad_s",
    "settle_counter_s",
    "target_reached",
    "terminal_failure_reward",
    "terminal_success_reward",
    "water_current_speed_m_s",
    "xy_drift_m",
    "xy_drift_penalty",
    "xy_error_w",
    "yaw_abs_error_rad",
    "yaw_hold_penalty",
]
